# Generated by Django 5.2.8 on 2025-11-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='mensage',
        ),
    ]
