# Generated by Django 5.2.8 on 2025-11-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_text_message_mensage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='self_message',
            field=models.BooleanField(default=False),
        ),
    ]
